drop table spell_dbc;
CREATE TABLE `spell_dbc` (
  `Id` int(11) NOT NULL DEFAULT '0', 
  `Category` int(11) NOT NULL DEFAULT '0',
  `castUI` int(11) NOT NULL DEFAULT '0',
  `Dispel` int(11) NOT NULL DEFAULT '0',
  `Mechanic` int(11) NOT NULL DEFAULT '0',
  `Attributes` bigint(11) NOT NULL DEFAULT '0',
  `AttributesEx` bigint(11) NOT NULL DEFAULT '0',
  `AttributesEx2` bigint(11) NOT NULL DEFAULT '0',
  `AttributesEx3` bigint(11) NOT NULL DEFAULT '0',
  `AttributesEx4` bigint(11) NOT NULL DEFAULT '0',
  `AttributesEx5` bigint(11) NOT NULL DEFAULT '0',
  `AttributesEx6` bigint(11) NOT NULL DEFAULT '0',
  `Stances` bigint(11) NOT NULL DEFAULT '0',
  `StancesNot` bigint(11) NOT NULL DEFAULT '0',
  `Targets` int(11) NOT NULL DEFAULT '0',
  `TargetCreatureType` int(11) NOT NULL DEFAULT '0',
  `RequiresSpellFocus` int(11) NOT NULL DEFAULT '0',
  `FacingCasterFlags` int(11) NOT NULL DEFAULT '0',
  `CasterAuraState` int(11) NOT NULL DEFAULT '0',
  `TargetAuraState` int(11) NOT NULL DEFAULT '0',
  `CasterAuraStateNot` int(11) NOT NULL DEFAULT '0',
  `TargetAuraStateNot` int(11) NOT NULL DEFAULT '0',
  `CastingTimeIndex` int(11) NOT NULL DEFAULT '0',
  `RecoveryTime` int(11) NOT NULL DEFAULT '0',
  `CategoryRecoveryTime` int(11) NOT NULL DEFAULT '0',
  `InterruptFlags` int(11) NOT NULL DEFAULT '0',
  `AuraInterruptFlags` int(11) NOT NULL DEFAULT '0',
  `ChannelInterruptFlags` int(11) NOT NULL DEFAULT '0',
  `procFlags` int(11) NOT NULL DEFAULT '0',
  `procChance` int(11) NOT NULL DEFAULT '0',
  `procCharges` int(11) NOT NULL DEFAULT '0',
  `maxLevel` int(11) NOT NULL DEFAULT '0',
  `baseLevel` int(11) NOT NULL DEFAULT '0',
  `spellLevel` int(11) NOT NULL DEFAULT '0',
  `DurationIndex` int(11) NOT NULL DEFAULT '0',
  `powerType` bigint(11) NOT NULL DEFAULT '0',
  `manaCost` int(11) NOT NULL DEFAULT '0',
  `manaCostPerlevel` int(11) NOT NULL DEFAULT '0',
  `manaPerSecond` int(11) NOT NULL DEFAULT '0',
  `manaPerSecondPerLevel` int(11) NOT NULL DEFAULT '0',
  `rangeIndex` int(11) NOT NULL DEFAULT '0',
  `speed` float NOT NULL DEFAULT '0',
  `modalNextSpell` int(11) NOT NULL DEFAULT '0',
  `StackAmount` int(11) NOT NULL DEFAULT '0',
  `Totem1` int(11) NOT NULL DEFAULT '0',
  `Totem2` int(11) NOT NULL DEFAULT '0',
  `Reagent1` int(11) NOT NULL DEFAULT '0',
  `Reagent2` int(11) NOT NULL DEFAULT '0',
  `Reagent3` int(11) NOT NULL DEFAULT '0',
  `Reagent4` int(11) NOT NULL DEFAULT '0',
  `Reagent5` int(11) NOT NULL DEFAULT '0',
  `Reagent6` int(11) NOT NULL DEFAULT '0',
  `Reagent7` int(11) NOT NULL DEFAULT '0',
  `Reagent8` int(11) NOT NULL DEFAULT '0',
  `ReagentCount1` bigint(11) NOT NULL DEFAULT '0',
  `ReagentCount2` int(11) NOT NULL DEFAULT '0',
  `ReagentCount3` int(11) NOT NULL DEFAULT '0',
  `ReagentCount4` int(11) NOT NULL DEFAULT '0',
  `ReagentCount5` int(11) NOT NULL DEFAULT '0',
  `ReagentCount6` int(11) NOT NULL DEFAULT '0',
  `ReagentCount7` int(11) NOT NULL DEFAULT '0',
  `ReagentCount8` int(11) NOT NULL DEFAULT '0',
  `EquippedItemClass` int(11) NOT NULL DEFAULT '0',
  `EquippedItemSubClassMask` int(11) NOT NULL DEFAULT '0',
  `EquippedItemInventoryTypeMask` int(11) NOT NULL DEFAULT '0',
  `Effect1` int(11) NOT NULL DEFAULT '0',
  `Effect2` int(11) NOT NULL DEFAULT '0',
  `Effect3` int(11) NOT NULL DEFAULT '0',
  `EffectDieSides1` int(11) NOT NULL DEFAULT '0',
  `EffectDieSides2` int(11) NOT NULL DEFAULT '0',
  `EffectDieSides3` int(11) NOT NULL DEFAULT '0',
  `EffectBaseDice1` int(11) NOT NULL DEFAULT '0',
  `EffectBaseDice2` int(11) NOT NULL DEFAULT '0',
  `EffectBaseDice3` int(11) NOT NULL DEFAULT '0',
  `EffectDicePerLevel1` int(11) NOT NULL DEFAULT '0',
  `EffectDicePerLevel2` int(11) NOT NULL DEFAULT '0',
  `EffectDicePerLevel3` int(11) NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel1` float NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel2` float NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel3` float NOT NULL DEFAULT '0',
  `EffectBasePoints1` int(11) NOT NULL DEFAULT '0',
  `EffectBasePoints2` int(11) NOT NULL DEFAULT '0',
  `EffectBasePoints3` int(11) NOT NULL DEFAULT '0',
  `EffectMechanic1` int(11) NOT NULL DEFAULT '0',
  `EffectMechanic2` int(11) NOT NULL DEFAULT '0',
  `EffectMechanic3` int(11) NOT NULL DEFAULT '0',
  `EffectImplicitTargetA1` int(11) NOT NULL DEFAULT '0',
  `EffectImplicitTargetA2` int(11) NOT NULL DEFAULT '0',
  `EffectImplicitTargetA3` int(11) NOT NULL DEFAULT '0',
  `EffectImplicitTargetB1` int(11) NOT NULL DEFAULT '0',
  `EffectImplicitTargetB2` int(11) NOT NULL DEFAULT '0',
  `EffectImplicitTargetB3` int(11) NOT NULL DEFAULT '0',
  `EffectRadiusIndex1` int(11) NOT NULL DEFAULT '0',
  `EffectRadiusIndex2` int(11) NOT NULL DEFAULT '0',
  `EffectRadiusIndex3` int(11) NOT NULL DEFAULT '0',
  `EffectApplyAuraName1` int(11) NOT NULL DEFAULT '0',
  `EffectApplyAuraName2` int(11) NOT NULL DEFAULT '0',
  `EffectApplyAuraName3` int(11) NOT NULL DEFAULT '0',
  `EffectAmplitude1` int(11) NOT NULL DEFAULT '0',
  `EffectAmplitude2` int(11) NOT NULL DEFAULT '0',
  `EffectAmplitude3` int(11) NOT NULL DEFAULT '0',
  `EffectMultipleValue1` float NOT NULL DEFAULT '0',
  `EffectMultipleValue2` float NOT NULL DEFAULT '0',
  `EffectMultipleValue3` float NOT NULL DEFAULT '0',
  `EffectChainTarget1` int(11) NOT NULL DEFAULT '0',
  `EffectChainTarget2` int(11) NOT NULL DEFAULT '0',
  `EffectChainTarget3` int(11) NOT NULL DEFAULT '0',
  `EffectItemType1` bigint(11) NOT NULL DEFAULT '0',
  `EffectItemType2` bigint(11) NOT NULL DEFAULT '0',
  `EffectItemType3` bigint(11) NOT NULL DEFAULT '0',
  `EffectMiscValue1` int(11) NOT NULL DEFAULT '0',
  `EffectMiscValue2` int(11) NOT NULL DEFAULT '0',
  `EffectMiscValue3` int(11) NOT NULL DEFAULT '0',
  `EffectMiscValueB1` int(11) NOT NULL DEFAULT '0',
  `EffectMiscValueB2` int(11) NOT NULL DEFAULT '0',
  `EffectMiscValueB3` int(11) NOT NULL DEFAULT '0',
  `EffectTriggerSpell1` int(11) NOT NULL DEFAULT '0',
  `EffectTriggerSpell2` int(11) NOT NULL DEFAULT '0',
  `EffectTriggerSpell3` int(11) NOT NULL DEFAULT '0',
  `EffectPointsPerComboPoint1` int(11) NOT NULL DEFAULT '0',
  `EffectPointsPerComboPoint2` int(11) NOT NULL DEFAULT '0',
  `EffectPointsPerComboPoint3` int(11) NOT NULL DEFAULT '0',
  `SpellVisual` int(11) NOT NULL DEFAULT '0',
  `SpellVisual2` int(11) NOT NULL DEFAULT '0',
  `SpellIconID` int(11) NOT NULL DEFAULT '0',
  `activeIconID` int(11) NOT NULL DEFAULT '0',
  `spellPriority` int(11) NOT NULL DEFAULT '0',
  `SpellName` text,
  `SpellName2` text,
  `SpellName3` text,
  `SpellName4` text,
  `SpellName5` text,
  `SpellName6` text,
  `SpellName7` text,
  `SpellName8` text,
  `SpellName9` text,
  `SpellName10` text,
  `SpellName11` text,
  `SpellName12` text,
  `SpellName13` text,
  `SpellName14` text,
  `SpellName15` text,
  `SpellName16` text,
  `SpellNameFlag` int(11) NOT NULL DEFAULT '0',
  `Rank` text,
  `Rank2` text,
  `Rank3` text,
  `Rank4` text,
  `Rank5` text,
  `Rank6` text,
  `Rank7` text,
  `Rank8` text,
  `Rank9` text,
  `Rank10` text,
  `Rank11` text,
  `Rank12` text,
  `Rank13` text,
  `Rank14` text,
  `Rank15` text,
  `Rank16` text,
  `RankFlags` int(11) NOT NULL DEFAULT '0',
  `Description` text,
  `Description2` text,
  `Description3` text,
  `Description4` text,
  `Description5` text,
  `Description6` text,
  `Description7` text,
  `Description8` text,
  `Description9` text,
  `Description10` text,
  `Description11` text,
  `Description12` text,
  `Description13` text,
  `Description14` text,
  `Description15` text,
  `Description16` text,
  `DescriptionFlags` int(11) NOT NULL DEFAULT '0',
  `ToolTip` text,
  `ToolTip2` text,
  `ToolTip3` text,
  `ToolTip4` text,
  `ToolTip5` text,
  `ToolTip6` text,
  `ToolTip7` text,
  `ToolTip8` text,
  `ToolTip9` text,
  `ToolTip10` text,
  `ToolTip11` text,
  `ToolTip12` text,
  `ToolTip13` text,
  `ToolTip14` text,
  `ToolTip15` text,
  `ToolTip16` text,
  `ToolTipFlags` int(11) NOT NULL DEFAULT '0',
  `ManaCostPercentage` int(11) NOT NULL DEFAULT '0',
  `StartRecoveryCategory` int(11) NOT NULL DEFAULT '0',
  `StartRecoveryTime` int(11) NOT NULL DEFAULT '0',
  `MaxTargetLevel` int(11) NOT NULL DEFAULT '0',
  `SpellFamilyName` int(11) NOT NULL DEFAULT '0',
  `SpellFamilyFlags1` bigint(11) NOT NULL DEFAULT '0',
  `SpellFamilyFlags2` bigint(11) NOT NULL DEFAULT '0',
  `MaxAffectedTargets` int(11) NOT NULL DEFAULT '0',
  `DmgClass` int(11) NOT NULL DEFAULT '0',
  `PreventionType` int(11) NOT NULL DEFAULT '0',
  `StanceBarOrder` int(11) NOT NULL DEFAULT '0',
  `DmgMultiplier1` float NOT NULL DEFAULT '0',
  `DmgMultiplier2` float NOT NULL DEFAULT '0',
  `DmgMultiplier3` float NOT NULL DEFAULT '0',
  `MinFactionId` int(11) NOT NULL DEFAULT '0',
  `MinReputation` int(11) NOT NULL DEFAULT '0',
  `RequiredAuraVision` int(11) NOT NULL DEFAULT '0',
  `TotemCategory1` int(11) NOT NULL DEFAULT '0',
  `TotemCategory2` int(11) NOT NULL DEFAULT '0',
  `AreaId` int(11) NOT NULL DEFAULT '0',
  `SchoolMask` int(11) NOT NULL DEFAULT '0',
  `IsServerSide` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Export of Spell.dbc';
